my $results = Modules->Forcite->Anneal->Run($doc, Settings(
	'3DPeriodicElectrostaticSummationMethod' => 'PPPM',
	'3DPeriodicvdWEwaldSumAccuracy' => 0.0001,
	'3DPeriodicElectrostaticEwaldSumAccuracy' => 1e-005,
	'3DPeriodicElectrostaticPPPMAccuracy' => 0.0001,
	'3DPeriodicvdWAtomCubicSplineCutOff' => 18.5,
	'3DPeriodicvdWChargeGroupCubicSplineCutOff' => 15.5,
	'3DPeriodicEAMAtomCubicSplineCutOff' => 15.5,
	MACEForcefieldSize => 'Large',
	CurrentForcefield => 'COMPASSIII',
	AssignForcefieldTypes => 'No',
	Ensemble3D => 'NVT',
	Temperature => 500,
	NumberOfSteps => 10000,
	TrajectoryFrequency => 1000,
	MidCycleTemperature => 700,
	StepsPerRamp => 1000,
	OptimizeAnnealedStructure => 'Yes'));
my $outTrajectory = $results->Trajectory;
my $outAnnealTrajectory = $results->AnnealTrajectory;
